apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: my-go-wasm-plugin
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  # TODO(incfly): replace this with an ghcr image once the artificats are available.
  url: oci://registry.cn-hangzhou.aliyuncs.com/USER_NAME/gowasm:{version}
  pluginConfig:
    testConfig: abcddeeeee
    listconfig:
     - abc
     - def